apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry
      containers:
        - name: api
          image: "ghcr.io/{{github_repo}}/api:{{ .Values.api.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            {{- include "{{name}}.apiEnv" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 15
            periodSeconds: 30
