apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-www
spec:
  replicas: {{ .Values.www.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-www
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-www
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-registry
      containers:
        - name: www
          image: "ghcr.io/{{github_repo}}/www:{{ .Values.www.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: APP_URL
              value: {{ .Values.www.app_url | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
